//Trabajos
export const OBTENER_TRABAJOS='OBTENER_TRABAJOS';

//Estudio
export const OBTENER_ESTUDIO_BY_CREATOR='OBTENER_ESTUDIO_BY_CREATOR';

//Auth
export const REGISTRO_EXITOSO= 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR= 'REGISTRO_ERROR';
export const LOGIN_EXITOSO= 'LOGIN_EXITOSO';
export const LOGIN_ERROR= 'LOGIN_ERROR';
export const OBTENER_USUARIO= 'OBTENER_USUARIO';
export const CERRAR_SESION= 'CERRAR_SESION';

//alertas
export const MOSTRAR_ALERTA= 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA= 'OCULTAR_ALERTA';
